### PR TITLE
WIP: Try explicit operator for macos fix

### PR DESCRIPTION
**Pull request by tbirdso**
I do not currently have a local macOS environment to reproduce [https://open.cdash.org/viewBuildError.php?buildid=7756812](https://open.cdash.org/viewBuildError.php?buildid=7756812). Will attempt to use CI for experimenting with a fix.

### CODE REVIEW

**Comment by tbirdso** [comment]
@dzenanz I believe CI failed on this one, probably best to revert.

**Comment by dzenanz** [comment]
This is all in my fork.

**Comment by tbirdso** [comment]
A hard reset to the previous commit, then?

**Comment by dzenanz** [comment]
No, I merged it on purpose. I will take a crack at this now, and I thought I would start from the latest WIP.

**Comment by tbirdso** [comment]
Understood, I believe the WIP simply introduced an additional bug 😅 but it is up to you how you would like to proceed.

**Pull request merged**
