### PR TITLE
BUG: Fix 1D spectra testing data

### PR DESCRIPTION
**Pull request by tbirdso**
Replaces single-pixel RF input with contrived 31-channel single pixel vector image input for baseline tests with "Spectra1D" classes.

This change will allow development on this branch to proceed with passing tests (which perhaps should be verified with CI before merge).

Partially addresses an issue where the last 2 out of 31 channels in the single pixel image `rf_voltage_15_freq_0005000000_2017-5-31_12-36-44_ReferenceSpectrum_side_lines_03_fft1d_size_128.mha` would sometimes change when read in with `itk::ImageFileReader`. Will enter an issue in ITK to track a full resolution via MetaImageIO.

### CODE REVIEW

**Comment by tbirdso** [comment]
Tracked in [https://github.com/InsightSoftwareConsortium/ITK/issues/3208](https://github.com/InsightSoftwareConsortium/ITK/issues/3208)

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
This does not compile on MacOS: `[include/itkSpectra1DNormalizeImageFilter.hxx:112](https://github.com/InsightSoftwareConsortium/ITK/blob/master/include/itkSpectra1DNormalizeImageFilter.hxx#L112):25: error: use of overloaded operator '/' is ambiguous (with operand types 'itk::ImageConstIterator<itk::Image<itk::Vector<float, 31>, 2> >::PixelType' (aka 'itk::Vector<float, 31>') and 'const itk::Vector<float, 31>')`. But this PR did not introduce it.

**Comment by dzenanz** [comment]
The Python test still fails on my computer, just with a slightly different number now:
```text
33: Loading Ultrasound... done
33: Loading ITKPyUtils... done
33: Running itkImageFileReaderVIF3... done
33: Running itkImageFileReaderVIF3... done
33: Running itkImageFileReaderVIF3... done
33: Running itkSpectra1DAveragingImageFilterVIF3VIF2... done
33: done
33: Running itkSpectra1DAveragingImageFilterVIF3VIF2... done
33: done
33: Running itkImageFileWriterVIF2... done
33: Reading C:/Dev/ITKUltrasound-2019/ExternalData/test/Input/spectra_pixel_image.mha
33: Reading C:/Dev/ITKUltrasound-2019/ExternalData/test/Input/spectra_pixel_image.mha
33: Reading C:/Dev/ITKUltrasound-2019/ExternalData/test/Input/spectra_pixel_image.mha
33: Executing the filter
33: Writing resulting image into file: C:/Dev/ITKUltrasound-2019/Testing/Temporary/PythonSpectra1DAveragingImageFilterTest.mha
33: Test finished
33: <DartMeasurement name="ImageError spectra_pixel_image.mha" type="numeric/double">1</DartMeasurement>
33: <DartMeasurement name="ImageError" type="numeric/double">1</DartMeasurement>
33: <DartMeasurement name="ImageError Minimum" type="numeric/double">8.5376e+27</DartMeasurement>
33: <DartMeasurement name="ImageError Maximum" type="numeric/double">8.5376e+27</DartMeasurement>
33: <DartMeasurement name="ImageError Mean" type="numeric/double">8.5376e+27</DartMeasurement>
33: <DartMeasurementFile name="DifferenceImage" type="image/png">C:/Dev/ITKUltrasound-2019/Testing/Temporary/PythonSpectra1DAveragingImageFilterTest.mha.diff.png</DartMeasurementFile>
33: <DartMeasurementFile name="BaselineImage" type="image/png">C:/Dev/ITKUltrasound-2019/Testing/Temporary/PythonSpectra1DAveragingImageFilterTest.mha.base.png</DartMeasurementFile>
33: <DartMeasurementFile name="TestImage" type="image/png">C:/Dev/ITKUltrasound-2019/Testing/Temporary/PythonSpectra1DAveragingImageFilterTest.mha.test.png</DartMeasurementFile>
33: <DartMeasurement name="BaselineImageName" type="text/string">spectra_pixel_image.mha</DartMeasurement>
2/2 Test #33: PythonSpectra1DAveragingImageFilterTest ...***Failed   24.99 sec

The following tests passed:
        itkSpectra1DAveragingImageFilterTest

50% tests passed, 1 tests failed out of 2

Label Time Summary:
Python        =  24.99 sec*proc (1 test)
Ultrasound    =  25.17 sec*proc (2 tests)

Total Test time (real) =  25.22 sec

The following tests FAILED:
         33 - PythonSpectra1DAveragingImageFilterTest (Failed)
```

**Comment by tbirdso** [comment]
@dzenanz FYI I'm investigating this but running into issues loading ITK Python external modules again. I was not able to run Python tests yesterday while rebuilding ITK. I believe I was mistaken in thinking CI would cover Python tests.

**Comment by tbirdso** [comment]
@dzenanz Based on my testing so far it looks like something is going wrong in Python's handling of adding `itk.VariableLengthVector`s with `+`. I've been able to get reliably correct output when I replace the operator with `+=`. I was surprised to see that the two operators seem to be entirely independently defined in ITK: [`+=`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkVariableLengthVector.h#L840) vs [`+`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkVariableLengthVector.h#L1265)

As you've already identified, addition operations are getting tricky between template types which may either be fixed or variable-size vectors, and I'm having trouble getting an SFINAE workaround approach to compile. The ideal solution here would be to introduce a fix in ITK proper to both 1) correct inconsistent `itk.VariableLengthVector + itk.VariableLengthVector` operations and 2) implement `itk.VariableLengthVector += itk.Vector` operation overloads (and vice versa). However, I don't have a good estimate of how long this might take. Do you have thoughts on how we should approach this?

**Comment by dzenanz** [comment]
I was wondering where `Plus` is defined. I think [here](https://github.com/InsightSoftwareConsortium/ITK/blob/047fa6934ac32711d1d7b84fa6eb81c72db01960/Modules/Core/Common/include/itkBinaryOperationConcept.h#L50).

I don't think the difference between Python and C++ can be explained by weirdness in C++ operators. Python does not look inside implementation of a class such as `Spectra1DAveragingImageFilter`. But then again, I don't have an explanation for it.

It would be good to have `+` and `+=` operators for combinations of VLV and regular Vector in ITK proper.

Maybe first look into [MetaImage reading bug](https://github.com/InsightSoftwareConsortium/ITK/issues/3208)? If that is not the root cause, it will at least eliminate one variable.

**Pull request merged**
